---
- name: playbook for deployment
  hosts: deployserver
  become: yes
  tasks:
    - name: deploying artifact
      copy:
        src: /var/lib/jenkins/workspace/deployment/mental.sh
        dest: /home/ubuntu1
        
     - name: deploying artifact1
       copy:
        src: /var/lib/jenkins/workspace/deployment/mental.sh
        dest: /home/client2   
      
    
        
...
